from pathlib import Path
p=Path('/home/testpilot/mim/scripts/mim_ready_task_dispatcher.py')
s=p.read_text()
old='''    if upper_key == "AGENTMIM-FORUM-IMAGE-AUTO-QA-REMEDIATION-V1":\n        return {\n            **base,\n            "packet_type": "mim-tod-objective-execution-evidence-v2",\n            "status": "queued_with_codex_implementation_request",\n            "reason_code": "forum_image_auto_qa_executor_requested",'''
new='''    if upper_key == "AGENTMIM-FORUM-IMAGE-AUTO-QA-REMEDIATION-V1":\n        result = load_json(SHARED / "AGENTMIM_FORUM_IMAGE_AUTO_QA_IMPLEMENTATION_RESULT.latest.json", {})\n        if result:\n            return {\n                **base,\n                "packet_type": "mim-tod-objective-execution-evidence-v2",\n                "status": "implementation_completed_with_local_validation",\n                "reason_code": "codex_result_ingested_database_apply_blocked",\n                "evidence_artifacts": ["runtime/shared/AGENTMIM_FORUM_IMAGE_AUTO_QA_IMPLEMENTATION_RESULT.latest.json"],\n                "codex_result_artifact": "runtime/shared/AGENTMIM_FORUM_IMAGE_AUTO_QA_IMPLEMENTATION_RESULT.latest.json",\n                "implementation_result": result,\n                "operator_facing_summary": "Forum image QA implementation is complete locally: weak generated editorial/MIM Opinion images now fail relevance and quality gates, and the remediation runner exists.",\n                "next_recovery_action": "Run forum-image-auto-qa-remediate --apply from the deployed AgentMIM environment with database access, then verify remediated post evidence.",\n                "expected_files": ["E:/comm_app/routes/routes.py", "E:/comm_app/app/services/forum_image_auto_qa.py", "E:/comm_app/scripts/run_forum_image_auto_qa_remediation.py", "runtime/shared/AGENTMIM_FORUM_IMAGE_QA_REMEDIATION_STATUS.latest.json"],\n                "validation_requirements": result.get("validation", []),\n                "confidence": "high",\n                "source": "mim_ready_task_dispatcher_forum_image_codex_result_intake",\n            }\n        return {\n            **base,\n            "packet_type": "mim-tod-objective-execution-evidence-v2",\n            "status": "queued_with_codex_implementation_request",\n            "reason_code": "forum_image_auto_qa_executor_requested",'''
if old not in s:
    raise SystemExit('forum branch needle missing')
s=s.replace(old,new)
s=s.replace('terminal_statuses = {"completed", "completed_with_evidence", "blocked_with_evidence", "blocked_with_escalation"}', 'terminal_statuses = {"completed", "completed_with_evidence", "blocked_with_evidence", "blocked_with_escalation", "implementation_completed_with_local_validation"}')
p.write_text(s)
print('patched direct forum branch and terminal statuses')