param(
    [Parameter(Mandatory = $true)][string]$PreviewTargetPlanPath,
    [string]$Source = "CodexSupervised::UserAppRuntimeScaffold"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot

function Convert-ToRepoPath {
    param([Parameter(Mandatory = $true)][string]$PathValue)
    if ([System.IO.Path]::IsPathRooted($PathValue)) {
        return $PathValue
    }
    return (Join-Path $repoRoot $PathValue)
}

function Convert-ToRepoRelativePath {
    param([Parameter(Mandatory = $true)][string]$PathValue)
    $fullPath = [System.IO.Path]::GetFullPath((Convert-ToRepoPath -PathValue $PathValue))
    $root = [System.IO.Path]::GetFullPath($repoRoot)
    if (-not $fullPath.StartsWith($root, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Path is outside repo root: $PathValue"
    }
    return ($fullPath.Substring($root.Length).TrimStart('\', '/') -replace '\\', '/')
}

function Write-Utf8NoBom {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Content
    )
    New-Item -ItemType Directory -Path (Split-Path -Parent $Path) -Force | Out-Null
    $utf8NoBom = [System.Text.UTF8Encoding]::new($false)
    [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

$planAbs = Convert-ToRepoPath -PathValue $PreviewTargetPlanPath
if (-not (Test-Path -Path $planAbs -PathType Leaf)) {
    throw "Preview target plan not found: $PreviewTargetPlanPath"
}
$plan = Get-Content -Path $planAbs -Raw | ConvertFrom-Json
if ([string]$plan.artifact_type -ne "user_app_preview_target_plan_v1") {
    throw "Unsupported preview target artifact type: $($plan.artifact_type)"
}

$repoAbs = Convert-ToRepoPath -PathValue ([string]$plan.repo_root)
$nextConfig = @"
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  output: "export",
  trailingSlash: true
};

export default nextConfig;
"@

$tsconfig = @"
{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }]
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
"@

$nextEnv = @"
/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by MIM/TOD app training.
"@

$gitignore = @"
node_modules
.next
out
coverage
*.log
.env
.env.local
"@

$styleTypes = @"
declare module "*.css";
"@

$manifest = [ordered]@{
    artifact_type = "user_app_runtime_scaffold_manifest_v1"
    generated_at = (Get-Date).ToUniversalTime().ToString("o")
    source = $Source
    app_name = [string]$plan.app_name
    slug = [string]$plan.slug
    source_preview_target_plan = Convert-ToRepoRelativePath -PathValue $planAbs
    repo_root = Convert-ToRepoRelativePath -PathValue $repoAbs
    files = @("next.config.mjs", "tsconfig.json", "next-env.d.ts", "src/types/styles.d.ts", ".gitignore")
    gates = [ordered]@{
        runtime_config = "ready"
        dependency_install = "not_run"
        local_build = "not_run"
        local_preview = "not_run"
        static_publish = "not_run"
        production_deploy = "not_selected"
    }
    dave_needed = "no"
    tod_next_action = "Install dependencies, run local build, start the preview target, and record runtime acceptance evidence."
}

Write-Utf8NoBom -Path (Join-Path $repoAbs "next.config.mjs") -Content $nextConfig
Write-Utf8NoBom -Path (Join-Path $repoAbs "tsconfig.json") -Content $tsconfig
Write-Utf8NoBom -Path (Join-Path $repoAbs "next-env.d.ts") -Content $nextEnv
Write-Utf8NoBom -Path (Join-Path $repoAbs "src/types/styles.d.ts") -Content $styleTypes
Write-Utf8NoBom -Path (Join-Path $repoAbs ".gitignore") -Content $gitignore
Write-Utf8NoBom -Path (Join-Path $repoAbs "runtime.manifest.json") -Content ($manifest | ConvertTo-Json -Depth 30)

$manifest | ConvertTo-Json -Depth 12
