param([string]$EnvFile = ".env")
Set-StrictMode -Version Latest
$ErrorActionPreference="Stop";$repoRoot=Split-Path -Parent $PSScriptRoot;$envPath=if([IO.Path]::IsPathRooted($EnvFile)){$EnvFile}else{Join-Path $repoRoot $EnvFile};$remoteRoot="/home/testpilot/mim"
$files=@(
    @{local="tmp_remote_mim/core/enterprise_discovery_service.py";remote="core/enterprise_discovery_service.py";before="9c383ebf34fdb3182b29690a0b93428766b6944be385d8544aafc3acfc58a1cb";after="0cac6cd56ca4fe409374c881c1bdf9e0d8dca208eb1e5b10ead453061f9c8cba"},
    @{local="tmp_remote_mim/core/enterprise_service.py";remote="core/enterprise_service.py";before="44262e5e3287966d1a594e35fe545089806288a87682c6853956c31a818b45e6";after="81844b298669a2622d83e4b81a54437184065516326ee219d2d291867361c52b"},
    @{local="tmp_remote_mim/core/routers/enterprises.py";remote="core/routers/enterprises.py";before="298000641fe0734869702ed78c6e4fdf91b17e30f8b4651debfeb3427b501d27";after="395b94bf4a5eb51d82c7d2afff8ff0646599db26f513a2789163c8adc5f7f3bd"},
    @{local="tmp_remote_mim/core/routers/project_portal.py";remote="core/routers/project_portal.py";before="ea9f25b29cba19a7a59330b70a49e13194c2ea492c8c0c5e0c3147884b69e074";after="925a05e309a0cce5176fed6a29901b4cb758b73d3efc231fbfb88a40237c2517"}
)
function Env([string]$n){$l=Get-Content $envPath|?{$_-match("^\s*{0}\s*="-f[regex]::Escape($n))}|select -First 1;if(!$l){return""};(($l-replace("^\s*{0}\s*=\s*"-f[regex]::Escape($n)),"").Trim().Trim('"'))}
function Remote([int]$id,[string]$cmd,[int]$timeout=120){$r=Invoke-SSHCommand -SessionId $id -Command $cmd -TimeOut $timeout;if($r.ExitStatus-ne 0){throw"Remote failed $($r.ExitStatus): $($r.Output-join' | ') $($r.Error-join'; ')"};$r}
function Upload([int]$id,[string]$local,[string]$dest){$enc=[Convert]::ToBase64String([IO.File]::ReadAllBytes((Resolve-Path(Join-Path $repoRoot $local))));$tmp="/tmp/ent208_$([guid]::NewGuid().ToString('N')).b64";for($o=0;$o-lt$enc.Length;$o+=12000){$c=$enc.Substring($o,[Math]::Min(12000,$enc.Length-$o));Remote $id "printf '%s' '$c' >> '$tmp'"|Out-Null};Remote $id "base64 -d '$tmp' > '$dest' && rm -f '$tmp'"|Out-Null}
Import-Module Posh-SSH;$cred=[pscredential]::new((Env 'MIM_SSH_USER'),(ConvertTo-SecureString (Env 'MIM_SSH_PASSWORD') -AsPlainText -Force));$pt=Env 'MIM_SSH_PORT';$s=New-SSHSession -ComputerName (Env 'MIM_SSH_HOST') -Port $(if($pt){[int]$pt}else{22}) -Credential $cred -AcceptKey -Force
try{$candidates=@();foreach($f in $files){$dest="$remoteRoot/scripts/ent208_$([IO.Path]::GetFileName($f.remote))";Upload $s.SessionId $f.local $dest;$current=([string]((Remote $s.SessionId "sha256sum '$remoteRoot/$($f.remote)' | awk '{print `$1}'").Output|select -First 1)).Trim();$candidate=([string]((Remote $s.SessionId "sha256sum '$dest' | awk '{print `$1}'").Output|select -First 1)).Trim();if($current-ne$f.before){throw"Remote guard failed $($f.remote): $current"};if($candidate-ne$f.after){throw"Candidate guard failed $($f.remote): $candidate"};$candidates+=@{spec=$f;path=$dest}}
    (Remote $s.SessionId "cd '$remoteRoot' && .venv/bin/python -m py_compile $($candidates.path -join ' ')").Output;$stamp=(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ');foreach($c in $candidates){$backup="$remoteRoot/$($c.spec.remote).bak.ent208-adapters.$stamp";(Remote $s.SessionId "cp '$remoteRoot/$($c.spec.remote)' '$backup' && cp '$($c.path)' '$remoteRoot/$($c.spec.remote)'").Output;"rollback=$backup"}
    (Remote $s.SessionId "cd '$remoteRoot' && .venv/bin/python -m py_compile core/enterprise_discovery_service.py core/enterprise_service.py core/routers/enterprises.py core/routers/project_portal.py && .venv/bin/python -c 'import core.app'").Output;(Remote $s.SessionId "systemctl --user restart mim-mobile-web.service mim-training-web.service").Output;(Remote $s.SessionId "for i in `$(seq 1 20); do a=`$(systemctl --user is-active mim-mobile-web.service); b=`$(systemctl --user is-active mim-training-web.service); if [ `"`$a`" = active ] && [ `"`$b`" = active ]; then echo `"`$a`";echo `"`$b`";exit 0;fi;sleep 2;done;exit 1" 60).Output;(Remote $s.SessionId "sha256sum $($files|%{"'$remoteRoot/$($_.remote)'"}-join' ')").Output
}finally{if($s){Remove-SSHSession $s.SessionId|Out-Null}}
