param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectId,
    [Parameter(Mandatory = $true)]
    [ValidateSet("image-generation", "graphics-creation", "ui-assets", "dynamic-visual-content", "short-video-animation", "diagram-dashboard-rendering", "vision-processing")]
    [string]$Capability,
    [Parameter(Mandatory = $true)]
    [string]$Prompt,
    [string]$OutputRelativePath,
    [string]$MediaCatalogPath = "tod/config/media-pipeline-profiles.json",
    [string]$RuntimePath = "tod/config/media-runtime.json",
    [string]$RegistryPath = "tod/config/project-registry.json",
    [string]$PriorityPath = "tod/config/project-priority.json",
    [switch]$Execute,
    [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$todScript = Join-Path $PSScriptRoot "TOD.ps1"
$policyScript = Join-Path $PSScriptRoot "Test-TODProjectAccessPolicy.ps1"

function Resolve-LocalPath {
    param([Parameter(Mandatory = $true)][string]$PathValue)
    if ([System.IO.Path]::IsPathRooted($PathValue)) { return $PathValue }
    return (Join-Path $repoRoot $PathValue)
}

function Get-JsonFile {
    param([Parameter(Mandatory = $true)][string]$PathValue)
    $resolved = Resolve-LocalPath -PathValue $PathValue
    if (-not (Test-Path -Path $resolved)) { throw "File not found: $resolved" }
    return (Get-Content -Path $resolved -Raw | ConvertFrom-Json)
}

function Get-ProjectExecutionMode {
    param(
        [Parameter(Mandatory = $true)][string]$ProjectId,
        [Parameter(Mandatory = $true)]$PriorityConfig
    )

    if (-not $PriorityConfig.PSObject.Properties["execution_order"]) {
        return "guarded-write"
    }

    $entry = @($PriorityConfig.execution_order | Where-Object { [string]$_.project_id -eq [string]$ProjectId } | Select-Object -First 1)
    if (@($entry).Count -eq 0 -or -not $entry[0].PSObject.Properties["mode"] -or [string]::IsNullOrWhiteSpace([string]$entry[0].mode)) {
        return "guarded-write"
    }

    return ([string]$entry[0].mode).ToLowerInvariant()
}

function Get-DefaultOutputRelativePath {
    param(
        $MediaSpec,
        [Parameter(Mandatory = $true)][string]$Capability
    )

    $timeSlug = (Get-Date).ToUniversalTime().ToString("yyyyMMdd-HHmmss")

    if ($Capability -eq "diagram-dashboard-rendering") {
        return "docs/generated/diagram-$timeSlug.svg"
    }

    if ($MediaSpec -and $MediaSpec.PSObject.Properties["output_paths"] -and @($MediaSpec.output_paths).Count -gt 0) {
        $base = ([string]$MediaSpec.output_paths[0] -replace "\\", "/").TrimStart("/")
        return "$base/asset-$timeSlug.json"
    }

    return "assets/output/asset-$timeSlug.json"
}

function New-DiagramSvg {
    param(
        [Parameter(Mandatory = $true)][string]$Title,
        [Parameter(Mandatory = $true)][string]$BodyText
    )

    $safeTitle = [System.Security.SecurityElement]::Escape($Title)
    $safeBody = [System.Security.SecurityElement]::Escape($BodyText)

    return @"
<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#0f172a"/>
      <stop offset="100%" stop-color="#134e4a"/>
    </linearGradient>
  </defs>
  <rect width="1280" height="720" fill="url(#bg)"/>
  <rect x="72" y="72" width="1136" height="576" rx="24" fill="#ffffff" fill-opacity="0.08"/>
  <text x="110" y="160" font-family="Segoe UI, Arial" font-size="46" fill="#f8fafc">$safeTitle</text>
  <text x="110" y="235" font-family="Consolas, monospace" font-size="24" fill="#bbf7d0">$safeBody</text>
  <text x="110" y="600" font-family="Segoe UI, Arial" font-size="20" fill="#86efac">Generated by TOD media pipeline</text>
</svg>
"@
}

if (-not (Test-Path -Path $todScript)) { throw "TOD script not found: $todScript" }
if (-not (Test-Path -Path $policyScript)) { throw "Policy script not found: $policyScript" }

$mediaCfg = Get-JsonFile -PathValue $MediaCatalogPath
$runtime = Get-JsonFile -PathValue $RuntimePath
$registry = Get-JsonFile -PathValue $RegistryPath
$priority = Get-JsonFile -PathValue $PriorityPath

$project = @($registry.projects | Where-Object { [string]$_.id -eq [string]$ProjectId } | Select-Object -First 1)
if (@($project).Count -eq 0) { throw "Project not found in registry: $ProjectId" }

$mediaItems = @()
if ($mediaCfg) {
    foreach ($prop in $mediaCfg.PSObject.Properties) {
        $candidate = @($prop.Value)
        if (@($candidate).Count -gt 0 -and $candidate[0].PSObject.Properties["project_id"]) {
            $mediaItems = $candidate
            break
        }
    }
}
$mediaEntry = @($mediaItems | Where-Object { [string]$_.project_id -eq [string]$ProjectId } | Select-Object -First 1)
$mediaSpec = if (@($mediaEntry).Count -gt 0) { $mediaEntry[0] } else { $null }

$executionMode = Get-ProjectExecutionMode -ProjectId $ProjectId -PriorityConfig $priority
$canExecute = $Execute -and ($executionMode -eq "guarded-write")
$effectiveDryRun = [bool]$DryRun -or (-not $canExecute)

$resolvedOutputRelativePath = if ([string]::IsNullOrWhiteSpace($OutputRelativePath)) {
    Get-DefaultOutputRelativePath -MediaSpec $mediaSpec -Capability $Capability
}
else {
    ([string]$OutputRelativePath -replace "\\", "/").TrimStart("/")
}

$policyRaw = & $policyScript -ProjectId $ProjectId -RelativePaths @($resolvedOutputRelativePath) -Operation "write"
$policy = $policyRaw | ConvertFrom-Json
if (-not $policy.ok) {
    throw "Policy denies output path for media pipeline: $resolvedOutputRelativePath"
}

$routeTarget = if ($runtime.routing.PSObject.Properties[$Capability]) { [string]$runtime.routing.$Capability } else { "comfyui" }

$jobId = "MEDIA-{0}" -f ([guid]::NewGuid().ToString("N").Substring(0, 10).ToUpperInvariant())
$generatedAt = (Get-Date).ToUniversalTime().ToString("o")

$manifest = [pscustomobject]@{
    id = $jobId
    generated_at = $generatedAt
    project_id = $ProjectId
    capability = $Capability
    execution_mode = $executionMode
    route_target = $routeTarget
    prompt = $Prompt
    output_relative_path = $resolvedOutputRelativePath
    runtime_defaults = if ($runtime.PSObject.Properties["defaults"]) { $runtime.defaults } else { $null }
    media_spec = $mediaSpec
}

$manifestJson = $manifest | ConvertTo-Json -Depth 20
$manifestPath = "{0}.manifest.json" -f $resolvedOutputRelativePath
$manifestSandboxPath = "projects/{0}/{1}" -f $ProjectId, $manifestPath
$outputSandboxPath = "projects/{0}/{1}" -f $ProjectId, $resolvedOutputRelativePath

$plannedActions = @()
$plannedActions += [pscustomobject]@{ action = "write-manifest"; sandbox_path = $manifestSandboxPath }

if ($Capability -eq "diagram-dashboard-rendering" -and $routeTarget -eq "code-svg") {
    $plannedActions += [pscustomobject]@{ action = "render-svg"; sandbox_path = $outputSandboxPath }
}
else {
    $plannedActions += [pscustomobject]@{ action = "dispatch-local-service"; target = $routeTarget; sandbox_path = $outputSandboxPath }
}

$writes = @()
$writes += [pscustomobject]@{
    sandbox_path = $manifestSandboxPath
    content = $manifestJson
}

if ($Capability -eq "diagram-dashboard-rendering" -and $routeTarget -eq "code-svg") {
    $svg = New-DiagramSvg -Title "TOD Diagram: $ProjectId" -BodyText $Prompt
    $writes += [pscustomobject]@{
        sandbox_path = $outputSandboxPath
        content = $svg
    }
}
elseif (-not $effectiveDryRun) {
    $dispatchRecord = [pscustomobject]@{
        status = "queued-for-local-service"
        route_target = $routeTarget
        prompt = $Prompt
        output_relative_path = $resolvedOutputRelativePath
        generated_at = $generatedAt
    } | ConvertTo-Json -Depth 10

    $writes += [pscustomobject]@{
        sandbox_path = $outputSandboxPath
        content = $dispatchRecord
    }
}

if (-not $effectiveDryRun) {
    foreach ($entry in $writes) {
        & $todScript -Action "sandbox-write" -SandboxPath ([string]$entry.sandbox_path) -Content ([string]$entry.content) | Out-Null
    }
}

$result = [pscustomobject]@{
    ok = $true
    source = "tod-media-pipeline-v1"
    generated_at = $generatedAt
    job_id = $jobId
    dry_run = $effectiveDryRun
    execute_requested = [bool]$Execute
    executed = (-not $effectiveDryRun)
    project_id = $ProjectId
    capability = $Capability
    execution_mode = $executionMode
    route_target = $routeTarget
    output_relative_path = $resolvedOutputRelativePath
    sandbox_output_path = $outputSandboxPath
    sandbox_manifest_path = $manifestSandboxPath
    planned_actions = @($plannedActions)
    policy = $policy
}

$result | ConvertTo-Json -Depth 20 | Write-Output
