param(
    [string]$ProjectIndexPath = "tod/data/project-library-index.json",
    [string]$RegistryPath = "tod/config/project-registry.json",
    [string]$SimulationArtifactPath = "shared_state/conversation_eval/github_project_simulation/tod_github_project_simulation.latest.json",
    [string]$FileName = "TOD.md",
    [switch]$EmitJson
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
function Resolve-LocalPath {
    param([Parameter(Mandatory = $true)][string]$PathValue)
    if ([System.IO.Path]::IsPathRooted($PathValue)) { return [System.IO.Path]::GetFullPath($PathValue) }
    return [System.IO.Path]::GetFullPath((Join-Path $repoRoot $PathValue))
}
function ConvertTo-RepoPath {
    param([Parameter(Mandatory = $true)][string]$PathValue)
    return (($PathValue -replace "[\\/]+", "/").Trim()).TrimStart("/")
}
function Test-PathPrefixMatch {
    param(
        [Parameter(Mandatory = $true)][string]$PathValue,
        [Parameter(Mandatory = $true)][string]$Prefix
    )

    $pathNorm = (ConvertTo-RepoPath -PathValue $PathValue).ToLowerInvariant()
    $prefixNorm = (ConvertTo-RepoPath -PathValue $Prefix).ToLowerInvariant()
    if ([string]::IsNullOrWhiteSpace($prefixNorm)) { return $false }
    return ($pathNorm -eq $prefixNorm -or $pathNorm.StartsWith($prefixNorm + "/"))
}
function Test-RelativePathAllowed {
    param(
        [Parameter(Mandatory = $true)][string]$RelativePath,
        [string[]]$AllowedPaths = @(),
        [string[]]$BlockedPaths = @()
    )

    $inAllowed = (@($AllowedPaths).Count -eq 0)
    foreach ($allowPrefix in @($AllowedPaths)) {
        if (Test-PathPrefixMatch -PathValue $RelativePath -Prefix ([string]$allowPrefix)) {
            $inAllowed = $true
            break
        }
    }

    foreach ($blockedPrefix in @($BlockedPaths)) {
        if (Test-PathPrefixMatch -PathValue $RelativePath -Prefix ([string]$blockedPrefix)) {
            return $false
        }
    }

    return $inAllowed
}
function Get-GitInfo {
    param([Parameter(Mandatory = $true)][string]$ProjectPath)
    $inside = $false; $branch = ""; $remote = ""; $status = "not-a-git-repo"
    try {
        $inside = ((& git -C $ProjectPath rev-parse --is-inside-work-tree 2>$null) -eq "true")
        if ($inside) {
            $branch = [string](& git -C $ProjectPath rev-parse --abbrev-ref HEAD 2>$null)
            $remote = [string](& git -C $ProjectPath remote get-url origin 2>$null)
            $status = [string](& git -C $ProjectPath status -sb 2>$null | Out-String).Trim()
        }
    } catch {}
    [pscustomobject]@{ is_repo = $inside; branch = $branch; remote_origin = $remote; status = $status }
}

$index = Get-Content -Path (Resolve-LocalPath -PathValue $ProjectIndexPath) -Raw | ConvertFrom-Json
$registry = Get-Content -Path (Resolve-LocalPath -PathValue $RegistryPath) -Raw | ConvertFrom-Json
$simPath = Resolve-LocalPath -PathValue $SimulationArtifactPath
$sim = if (Test-Path $simPath) { Get-Content -Path $simPath -Raw | ConvertFrom-Json } else { $null }

$written = @()
foreach ($proj in @($registry.projects)) {
    $idxProj = @($index.projects | Where-Object { [string]$_.id -eq [string]$proj.id } | Select-Object -First 1)
    $git = Get-GitInfo -ProjectPath ([string]$proj.path)
    $simScenario = if ($sim) { @($sim.scenarios | Where-Object { [string]$_.project_id -eq [string]$proj.id } | Select-Object -First 1) } else { $null }
    $entryPoints = if ($proj.entry_points) { @($proj.entry_points) } else { @() }
    $tests = if ($proj.test_commands) { @($proj.test_commands) } else { @() }
    $allowed = if ($proj.boundaries -and $proj.boundaries.allowed_paths) { @($proj.boundaries.allowed_paths) } else { @() }
    $blocked = if ($proj.boundaries -and $proj.boundaries.blocked_paths) { @($proj.boundaries.blocked_paths) } else { @() }
    $sampled = @()
    if ($idxProj -and $idxProj.discovery -and $idxProj.discovery.sampled_files) {
        $sampled = @(
            $idxProj.discovery.sampled_files |
                Where-Object {
                    Test-RelativePathAllowed -RelativePath ([string]$_) -AllowedPaths $allowed -BlockedPaths $blocked
                } |
                Select-Object -First 10
        )
    }

    $lines = @()
    $lines += "# TOD"
    $lines += ""
    $lines += "Generated by TOD project familiarization. Update this file after major work so TOD always has current status context."
    $lines += ""
    $lines += "## Current Status"
    $lines += "- Project: $([string]$proj.name)"
    $lines += "- Project ID: $([string]$proj.id)"
    $lines += "- Path: $([string]$proj.path)"
    $lines += "- Type: $([string]$proj.type)"
    $lines += "- Risk Level: $([string]$proj.risk_level)"
    $lines += "- Write Access: $([string]$proj.write_access)"
    $lines += "- Last Reviewed: $((Get-Date).ToUniversalTime().ToString('o'))"
    $lines += ""
    $lines += "## Git / Publish"
    $lines += "- Git Repo: $([string]$git.is_repo)"
    $lines += "- Branch: $([string]$git.branch)"
    $lines += "- Remote: $([string]$git.remote_origin)"
    if ($simScenario) {
        $lines += "- Simulation Publish Ready: $([string]$simScenario.publish_ready)"
        $lines += "- Simulation Discovery Passed: $([string]$simScenario.discovery_passed)"
        $lines += "- Simulation Candidate Files: $((@($simScenario.candidate_files) -join ', '))"
    }
    $lines += ""
    $lines += "## Entry Points"
    foreach ($entry in $entryPoints) { $lines += "- $entry" }
        if (@($entryPoints).Count -eq 0) { $lines += "- none recorded" }
    $lines += ""
    $lines += "## Test Commands"
    foreach ($test in $tests) { $lines += "- $test" }
        if (@($tests).Count -eq 0) { $lines += "- none recorded" }
    $lines += ""
    $lines += "## Boundaries"
    $lines += "### Allowed Paths"
    foreach ($a in $allowed) { $lines += "- $a" }
        if (@($allowed).Count -eq 0) { $lines += "- none recorded" }
    $lines += "### Blocked Paths"
    foreach ($b in $blocked) { $lines += "- $b" }
        if (@($blocked).Count -eq 0) { $lines += "- none recorded" }
    $lines += ""
    $lines += "## Sampled Files"
    foreach ($sample in $sampled) { $lines += "- $sample" }
        if (@($sampled).Count -eq 0) { $lines += "- none sampled" }
    $lines += ""
    $lines += "## TOD Notes"
    $lines += "- Use this file as the default current-status summary for TOD work in this project."
    $lines += "- Append work summary, commit references, and deployment notes after each significant task."
    $lines += "- Prefer discovery -> test -> minimal diff -> commit -> push -> verify workflow."
    $lines += ""
    $lines += "## TOD Activity Log"
    $lines += "- $((Get-Date).ToUniversalTime().ToString('o')) initial familiarization snapshot generated."

    $target = Join-Path ([string]$proj.path) $FileName
    Set-Content -Path $target -Value ($lines -join "`r`n")
    $written += [pscustomobject]@{ project_id = [string]$proj.id; path = $target }
}

$result = [pscustomobject]@{
    generated_at = (Get-Date).ToUniversalTime().ToString("o")
    file_name = $FileName
    project_count = @($written).Count
    written = @($written)
}
if ($EmitJson) { $result | ConvertTo-Json -Depth 12 | Write-Output } else { $result }
